### ISSUE TITLE
I can't install it.

### ISSUE THREAD

**Issue by Zhxhh** [Paradoxis/Flask-Unsign#1]
`I am using macOS
`The result of commands that I ran are as follows.

`
>pip install flask-unsign[wordlist]
zsh: no matches found: flask-unsign[wordlist]
`
`
> pip install flask-unsign
Collecting flask-unsign
Could not find a version that satisfies the requirement flask-unsign (from versions: )
No matching distribution found for flask-unsign
`

**Comment by Paradoxis** [comment]
Flask-Unsign is built for Python 3.6 and newer, the default pip binary on MacOS is that of Python 2.7, can you try it with:

    python3.6 -m pip install flask-unsign

**Comment by Zhxhh** [comment]
Thanks a lot!
It solved my problem!

**Comment by Zhxhh** [comment]
> Flask-Unsign is built for Python 3.6 and newer, the default pip binary on MacOS is that of Python 2.7, can you try it with:
> 
> ```
> python3.6 -m pip install flask-unsign
> ```

Thanks a lot!
It solved my problem!

**Comment by Paradoxis** [comment]
Good to hear :)
