### ISSUE TITLE
flask-unsign error

### ISSUE THREAD

**Issue by sharenjun** [Paradoxis/Flask-Unsign#12]
flask-unsign.exe -u -c "eyJ1c2VyIjoiaW1uZG0ifQ.YyVJCQ.UT6PNjMlkYujqXzF2pfbnQgbpBk" --wordlist .\Desktop\dict.txt
[*] Session decodes to: {'user': 'imndm'}
[*] Starting brute-forcer with 8 threads..
[!] Unhandled exception in cracker thread. Please report this issue on the official bug tracker: "https://github.com/Paradoxis/Flask-Unsign/issues" and don't forget to include the following traceback:

## Stack Trace
```
FlaskUnsignException: Secret must be a string-type (bytes, str) and received 'int'. To fix this, either add quotes to the secret 1111 or use the --no-literal-eval argument.
  File "E:\TOOLS\py3.9.9\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "E:\TOOLS\py3.9.9\lib\site-packages\flask_unsign\cracker.py", line 69, in unsign
    if session.verify(self.session, secret, legacy=self.legacy, salt=self.salt):
  File "E:\TOOLS\py3.9.9\lib\site-packages\flask_unsign\session.py", line 29, in verify
    raise FlaskUnsignException(
```

**Comment by Paradoxis** [comment]
Please read the error message and the FAQ on the tool's GitHub page. Your wordlist contains a line which isn't enclosed in quotes, hence the application fails to load it. If you're using a wordlist which doesn't live up to these standards, use the `--no-literal-eval` argument.
