### ISSUE TITLE
Empty string should be allowed for secret parameter by default

### ISSUE THREAD

**Issue by mellash** [Paradoxis/Flask-Unsign#17]
# Feature request
This feature request may not be that much nessary or an issues with the code, but I found it difficult for signing a cookie with empty string for flask app that doesn't use secret key at all.

## The code I run
> `flask-unsign --sign --cookie "{'email': 'ed@artificialuniversity.htb', 'loggedin': True, 'role': 'admin', 'user_id': 2}" --secret ''`
## The error I got
> `[!] Missing required parameter "--secret".`
## Current error
![ss-20241203-104216Z-selected](https://github.com/user-attachments/assets/4f8dddd3-19cc-42ae-8601-ad105cc0d081)
## What I suggest
![ss-20241203-105706Z-selected](https://github.com/user-attachments/assets/ba829719-976b-4832-89e1-84b8fcf4c69e)

**Comment by Paradoxis** [comment]
Oh funny, never knew Flask would actually allow empty secrets, I’ll fix it later today :), thanks for the report

**Comment by mellash** [comment]
Already made a pull request :) also thank you for creating such awesome tool :heart:

**Comment by Paradoxis** [comment]
Heya, thanks for the kind words and PR! I decided to slightly change it, add a helpful message and add some unit tests while I was at it :)
