### ISSUE TITLE
-w Unable to process Numbers in a dictionary

### ISSUE THREAD

**Issue by 851579181** [Paradoxis/Flask-Unsign#3]
![image](https://user-images.githubusercontent.com/20204019/79419913-5a2a0700-7fea-11ea-8e5f-d6dc67829489.png)

**Fix:**
session.verify(self.session, secret, legacy=self.legacy, salt=self.salt)
session.verify(self.session, **str(**secret**)**, legacy=self.legacy, salt=self.salt)

**Comment by Paradoxis** [comment]
Thanks for the bug report! I'll fix it and publish an updated version later today

It should be noted however that the wordlist should be a file with quoted python strings as it allows for binary strings to be put on one line, you can use `--no-literal-eval` argument to prevent the tool from loading the value incorrectly (see docs)

**Comment by 851579181** [comment]
Thanks for reminding me. It was my oversight.

**Comment by Paradoxis** [comment]
Fixed in commit c601a15
