### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 866: invalid continuation byte

### ISSUE THREAD

**Issue by nella17** [Paradoxis/Flask-Unsign#4]
# What went wrong?

I ran flask-unsign with rockyou.txt wordlist to brute force secret, but I got `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 866: invalid continuation byte`

## Stack Trace
If you got a stack trace, please paste it here:

```
...
```

## To Reproduce
Please add the following files / info:

- wordlist: https://github.com/danielmiessler/SecLists/blob/master/Passwords/Leaked-Databases/rockyou.txt.tar.gz
- cookie: `eyJlbmQiOiIyMDIwLTA3LTEzIDE2OjU5OjU5KzAwMDAifQ.XwxvHw.Nue9ROjhihVeTl5AwVhixO3vf5M`
- secret: `Time`

## System information
Please add the output of the following commands:

### Flask-Unsign Version
```
$ pip3 freeze | grep -i flask-unsign
flask-unsign==0.0.3
flask-unsign-wordlist==0.0.3

$ flask-unsign --version
0.0.3
```

### Flask-Unsign Type
```
$ file $(which flask-unsign)
/usr/local/bin/flask-unsign: a /usr/local/opt/python/bin/python3.7 script text executable, ASCII text
```

### Python Version
```
$ python3 --version
Python 3.7.7
```

### System Version
```
$ uname -a
Darwin Allens-MacBook-Pro.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64

$ cat /etc/issue
...
```

## Screenshots
A picture tells a thousand words, feel free to add one here if you have it

<img width="1021" alt="image" src="https://user-images.githubusercontent.com/14134195/87324682-071d0d00-c563-11ea-977a-b6862154f745.png">

## Other stuff
Got any other info I should know about? Have a monkeypatch or proposed fix?  <br>
Feel like ranting about something? Feel free to do it here. Compliments are also welcome ✨

**Comment by Paradoxis** [comment]
Thanks for submitting! I’ll check it out later tonight

**Comment by nella17** [comment]
Update try brute cookie and secret

**Comment by nella17** [comment]
This secret not in wordlist, but the bug is still exist.

**Comment by Paradoxis** [comment]
Managed to reproduce the bug, looking for a fix now

**Comment by Paradoxis** [comment]
Bug should now be fixed and you should notice a huge performance boost as well, you can use the following command to update to 0.1.0:

```
$ pip install -U flask-unsign 
```

**Comment by nella17** [comment]
Thanks
