### ISSUE TITLE
Ignore Bad SSL certs

### ISSUE THREAD

**Issue by random-robbie** [Paradoxis/Flask-Unsign#5]
Hey,

Would it be possible to add in something to ignore bad SSL certs.

Example when you fire `flask-unsign -u --server http://8.8.8.8` and the cert is only for the url you get errors.

adding the below to any file that uses requests and adding `verify=False` to any request should sort the issue out.

```
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
```

Keep up the good work!!

**Comment by Paradoxis** [comment]
Sounds like something that's not too hard to add, I'll have to see when I have some free time but I'll try adding it later this week :) 

Thanks!

**Comment by Paradoxis** [comment]
Imlemented in version 1.0.0, enjoy!
