### ISSUE TITLE
Question: Add output write to file

### ISSUE THREAD

**Issue by random-robbie** [Paradoxis/Flask-Unsign#6]
Hey,

Would it be possible to add an addition where if a key is successfully cracked the output is written to file.

I've noticed using `flask-unsign -k -u --server http://localhost:5000 | tee file.txt` is not great

Regards,
Robbie

**Comment by random-robbie** [comment]
added a PR 

https://github.com/random-robbie/Flask-Unsign/tree/patch-2

**Comment by Paradoxis** [comment]
Good idea, although I definitely appreciate the PR it still lacks some unit tests, code style things and could probably better be renamed to `-o` or `--output`. I'll get to writing my own implementation in a bit :)

**Comment by Paradoxis** [comment]
Implemented in 70b75c0 (version 1.1.0)
