### ISSUE TITLE
Brute-Force Key.

### ISSUE THREAD

**Issue by random-robbie** [Paradoxis/Flask-Unsign#8]
Hey,

would it be possible to add brute-force option at all?

I use flask-unsign for apache airflow bruteforce and have found how they generate the key for the cookie.

they use `b64encode(os.urandom(16)).decode('utf-8')`  and then decode it.

I'm basing this off the following commit.

https://github.com/apache/airflow/commit/f7602f8266559e55bc602a9639e3e1ab640f30e8

Regards,
Robbie

**Comment by Paradoxis** [comment]
Hey,

While I like the idea you’re probably better off just using other tools for generating wordlists or piping the output of a script to the `--wordlist` argument as it exceeds the scope of this project.

There’s a whole bunch of tools on GitHub that are much faster and better than anything I’ll ever make, you could try something like this:

```
$ flask-unsign --cookie ‘….’ --no-literal-eval --wordlist <(python3 generate-keys.py)
```
